### ISSUE TITLE
From FCBH: Problems Entering User/Pass

### ISSUE THREAD

**Issue by syedkarim** [Outernet-Project/librarian#335] opened 2016-07-22 04:06 UTC
Yesterday, I (Sally) could not successfully log into the Lantern unit.  I clicked on Login, but when I clicked on the Username box, it did not bring up a keyboard.  Instead, it closed the login window.  This occurred multiple times.  The device I was using is a Samsung SM-S820L, Android v4.4.4

**Comment by integricho** [comment] 2016-07-22 15:17
Tried reproducing the problem on Android 4.1.2, 5.0 and 6.0. On all versions it worked as expected, login dialog does not disappear unless clicking on an area that is outside of the login dialog itself. Clicking the text box brought up the keyboard in all cases while clicking on the area of the dialog itself doesn't do anything, it just stays up.

**Comment by foxbunny** [comment] 2016-07-22 15:23
Possible explanation if it was a single-handed use, that they touched the close overlay along the edge of the screen.

**Comment by foxbunny** [comment] 2016-08-26 08:37
Unable to reproduce and no further info, so closing.

**Closed by foxbunny** 2016-08-26 08:37 UTC
Labels: bug, invalid, user interface
